### ISSUE TITLE
keyup.esc on IE 11 does not seem to work

### ISSUE THREAD

**Issue by shaydoc** [shentao/vue-global-events#11]
My Function does not fire on IE 11
I am testing on Parallels for Mac on IE11, and its simply not firing on ``esc``

```
<global-events
        @keyup.esc="close"
      />
```

**Comment by shentao** [comment]
Does it only happen with the `esc` key?

**Comment by posva** [comment]
Turns out in the code generated by Vue: `_k($event.keyCode, "esc", 27, $event.key, "Escape"))`, `esc` do not match IE `Esc`. A workaround is to use `keyup.27` but this is a bug in Vue. It's weird because I remember it working on inputs so maybe IE11 is simply inconsistent if adding the event to an input or to the document

**Comment by shaydoc** [comment]
@shentao I think it's any modifier, I tried 27, then ```space``` the event object is alot different on IE11, I need to dig deeper

**Comment by shentao** [comment]
Please let us know if you find anything @shaydoc!

**Comment by posva** [comment]
Closing as there is nothing actionable for us in vue-global-events

**Comment by shaydoc** [comment]
@posva are saying that the issue lies with Vue itself?

**Comment by posva** [comment]
Yep! We cannot modify the code generated from here

**Comment by shaydoc** [comment]
@posva  this works!!
``` 
 const handler = e => {
          let evt = e;
          if (e.key === 'Esc') {
            evt = { ...e, keyCode: 27, key: 'Escape' }
          }
        this.filter(evt, listener, event) && listener(evt)
      }
```

**Comment by posva** [comment]
wait, I need to check if Vue does some monkey patching for this. I will check when I can

**Comment by shaydoc** [comment]
same for space, ```key``` comes out as ```Spacebar```

**Comment by posva** [comment]
that release only included a security fix. It may have not been released yet. Should come out soon

**Comment by posva** [comment]
This was fixed in Vue latest release :)
