### ISSUE TITLE
Add typescript declaration

### ISSUE THREAD

**Issue by Risto-Stevcev** [shentao/vue-global-events#141]
Can't use this with vue-cli
```
29:26 Could not find a declaration file for module 'vue-global-events'. '/Users/risto/git/foo/node_modules/vue-global-events/dist/vue-global-events.cjs.js' implicitly has an 'any' type.
  Try `npm install @types/vue-global-events` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-global-events';`
```

**Comment by posva** [comment]
This should be a good first issue. It requires to add a `types` property to the package.json and create a `vue-global-events.d.ts` file at the root of the project exporting a Vue `Component` as the default

**Comment by manniL** [comment]
@posva Can this be closed as types are available now (https://github.com/shentao/vue-global-events/blob/master/src/GlobalEvents.ts)?
