### ISSUE TITLE
Event listeners are not removed when using capture modifier

### ISSUE THREAD

**Issue by ropez** [shentao/vue-global-events#16]
Reproduced here: https://codesandbox.io/s/mm1jq18yx

When using the `.capture` modifier, the event listener is not removed when the component is destroyed. Each time the component is toggled, an additional handler is added.

I want to use this feature, because I want to have a global even handler, that in some cases will pass the even on to the active component.

**Comment by shentao** [comment]
Thanks for reporting! Should be an easy fix.

**Comment by shentao** [comment]
Fixed in v1.1.1 😃
