### ISSUE TITLE
Unexpected event behaviour with vue@2.6.0

### ISSUE THREAD

**Issue by cosminlupu** [shentao/vue-global-events#17]
### Version
`vue-global-events`: 1.1.1
`vue`: anything above `2.6.0-beta.1`

### Steps to reproduce
Use an inline expression to set a boolean value inside the `key` data of the component. The value of it starts as being false.
```js
<a href="#" @click="key = !key">Example</a>
```

Have a global event listener that is only active if `key` is `true`.

```js
<global-events
    v-if="key"
    @click="key = false"
/>
```

### What is expected?
Clicking the link will set `key` to `true` if it starts by being `false`. The handler for the global events should not be triggered. This is behaviour in `vue@2.15.22` and below.

### What is actually happening?
`key` is set to `true` by the handler of the link click event. The global events handler is also triggered and `key` is set to `false`, right after the initial event of the `a` tag.

**Comment by posva** [comment]
this is due to the micro to macro change. You will have to use `capture` modifier in one of the click events to ensure order

**Comment by shentao** [comment]
@posva although `capture` might solve the issue, I think we would need to figure out how to describe it nicely in the docs since this might sound like a pretty common use case.

**Comment by cosminlupu** [comment]
I understand the use of `capture`, but that doesn't solve the issue, as the behaviour will still not be the same as before the update. Why is there a difference in behaviour between vue@2.15.17 and vue@2.6.0 ?

**Comment by posva** [comment]
the difference is explained in Vue release notes
`capture` does remove the issue you are facing (I tested on the demo fiddle), I'm interested in seeing if it doesn't so we can provide a solution in the readme as @shentao pointed out
