### ISSUE TITLE
Doesn't work with vue 3

### ISSUE THREAD

**Issue by akarelas** [shentao/vue-global-events#172]
Even the simplest empty invocation of VueGlobalEvents (`<GlobalEvents />`) in a vue 3 app will render a blank page with an uncaught error in the console log.

**Comment by shentao** [comment]
Interesting! Thank you for reporting. Will look it up during the weekend most likely. Or if you want, you can try to debug it and provide a PR with a fix :)

**Comment by posva** [comment]
It does: https://github.com/shentao/vue-global-events/tree/next. I will add a link on the readme

FYI: as a maintainer, we cannot help if you don't at the very very least provide a stack trace

**Comment by shentao** [comment]
Uh, I assumed he meant the next version...

**Comment by akarelas** [comment]
The next version works fine. Thanks.
