### ISSUE TITLE
How to `stopPropagation` and `preventDefault` on all listeners?

### ISSUE THREAD

**Issue by mesqueeb** [shentao/vue-global-events#19]
I have about 40 key listeners set up, and on all of these I want to do
`event.stopPropagation()`  and `event.preventDefault()` .

How can I do this without having to attach `.stop.prevent` to all of these?

**Comment by mesqueeb** [comment]
I went with this method.
Maybe it can be added to the ReadMe.
```html
<GlobalEvents
      :filter="filterGlobalEvents"
```
```js
filterGlobalEvents (event, handler, eventName) {
      const el = event.target
      const elFocussed = (el.nodeName === 'INPUT' ||
        el.nodeName === 'TEXTAREA' ||
        el.nodeName === 'A' ||
        el.nodeName === 'BUTTON')
      if (elFocussed) return false
      event.preventDefault()
      event.stopPropagation()
      return true
    },
```

**Comment by posva** [comment]
Using the filter is the only way now, as with #20 a prop could be added for `prevent` and `stop` maybe also `capture`

**Comment by mesqueeb** [comment]
@posva Thanks. I had stop using my method, because I realised it was blocking all other hotkey's as well!!

Anyway, this is how my config looks like:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/3253920/54066015-1653c280-426c-11e9-938f-e8369dfa02aa.png">


I was thinking, there's no way I have a list of all the key-combinations I define inside `Global Events`. If you could pass on a 4th parameter to the filter event like so:
```js
filterGlobalEvents (event, handler, eventName, arrayOfDefinedKeyCombinations) 
```

Then I could write the filter so that `event.stopPropagation()` and `event.preventDefault()` is only triggered when the key combination is included in the `arrayOfDefinedKeyCombinations`.

**Comment by mesqueeb** [comment]
One other way would be to define a new prop/event for `GlobalEvents` where we could pass on stuff like 
so:
```vue
<GlobalEvents
  @custom-keydown.m="move"
/>
```
And have some sort of settings file where we can define what default modifiers this `custom-keydown` listener should get.
