### ISSUE TITLE
How to apply `.exact` on all listeners?

### ISSUE THREAD

**Issue by mesqueeb** [shentao/vue-global-events#20]
I have about 50+ listeners, all who need the `.exact` extension.
Is there a way to enable `exact` by default, so my code becomes more readable?
Thanks!

**Comment by posva** [comment]
Right now you would have to use a similar approach as in #19 by looking out for unused modifiers. Check the generated code by Vue: https://template-explorer.vuejs.org/#%3Cbutton%20%40keyup.ctrl.shift.a.exact%3D%22hey%22%3EHey%3C%2Fbutton%3E
try removing the `exact` to see the line you would need to add. You would have to check `eventName` for the different modifiers and filter the rest out.

I feel that adding a prop for this would maybe increase the amount of code too much but I haven't tried implementing it so I may be wrong

**Comment by posva** [comment]
After further investigation this is not technically possible because we have no access to all modifiers at runtime 😔
