### ISSUE TITLE
Is this also available as a mixin / global plugin?

### ISSUE THREAD

**Issue by davestewart** [shentao/vue-global-events#22]
It would be nice to be able to do something like this:

```
{
  mixins: [ globalEvents({ ... }) ]
}
```
Or even:

```
{
  events: {
    ...
  }
}
```

It feels a bit weird doing this in the view.

**Comment by posva** [comment]
Thanks for the he proposal but this doesn't align with current implementation, which is declarative and based on templates to use vue generated code for event modifiers and such. If used outside of the template we loose the most important part of it

**Comment by davestewart** [comment]
>  to use vue generated code for event modifiers and such

Fair point!
