### ISSUE TITLE
is Vue 2 still supported ?

### ISSUE THREAD

**Issue by theRenard** [shentao/vue-global-events#283]
I've tested your example downgrading to vue 2.7.10 and it doesn't work (but no errors in console sadly) So I wonder if it's still supported. 

If only vue 3 is supported please update the doc to make it explicit

**Comment by posva** [comment]
It is supported in v1: https://jsfiddle.net/posva/j2uc3dkv/, v2 is vue 3 only
Updated the demo for Vue 3
