### ISSUE TITLE
Version in dist items is not up to date

### ISSUE THREAD

**Issue by suterma** [shentao/vue-global-events#290]
### Additional information

This maybe nitpicking and not a functional problem but a documentation issue. It initially got me wondering whether my project's build process was broken:

The header of all items in the dist folder of the npm package of vue-global-event is still saying "v2.1.0" when in fact, the release is "v2.1.1". See directly in the npm package or via their online source browser: https://www.npmjs.com/package/vue-global-events?activeTab=explore

I suggest updating and releasing a fix with version 2.1.2.

**Comment by posva** [comment]
This should be fixed in the release script but it’s not a bug as it’s just a comment and people shouldn’t worry about it
