### ISSUE TITLE
Blur event not working

### ISSUE THREAD

**Issue by barvirm** [shentao/vue-global-events#292]
### Reproduction

https://jsfiddle.net/otqs5d67/7/

### Steps to reproduce the bug

1. Click on page in browser
2. Press ctrl+f
3. It's should get blur event

* If you remove a comment on `window.addEventListener` you will get the blur event.

### Expected behavior

`@blur` to work as `window.addEventListener('blur', ...)`

### Actual behavior

Event callback it's never called

**Comment by posva** [comment]
You need to set the target to window since it defaults to document

```vue
  <global-events
    target="window"
    @keydown.prevent.control="console.log('down')"
    @blur="console.log('blur')"
  ></global-events>
```
