### ISSUE TITLE
support for addEventListeners() third argument useCapture / options?

### ISSUE THREAD

**Issue by rodneyrehm** [shentao/vue-global-events#5]
right now `@focus.capture="…"` wouldn't work because the [focus event](https://developer.mozilla.org/en-US/docs/Web/Events/focus) can only be observed during the capture phase. Same goes for the `{ passive: true }` flag. see [addEventListener()](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener)

**Comment by posva** [comment]
Ah, that's true, we don't handle those

**Comment by shentao** [comment]
@rodneyrehm Just so you know – those are now supported in 1.0.1 thanks to @posva :)
