### ISSUE TITLE
Listening to `/` is broken on firefox though working when bound with `mousetrap`

### ISSUE THREAD

**Issue by manniL** [shentao/vue-global-events#58]
Listening globally on `/` won't work on Firefox as it will trigger the "Quick Search" functionality by default. However, `mousetrap` can successfully bind `/` to a function globally.

Could one possibly adapt the approach `mousetrap` uses? :thinking: 

Related issue: https://github.com/nuxt/nuxtjs.org/issues/233

**Comment by posva** [comment]
The `/` character is working fine when trying nuxtjs.org on Firefox

Regarding shortcuts, see https://github.com/shentao/vue-global-events#advice--caveats
