### ISSUE TITLE
Filter feature not in npm release

### ISSUE THREAD

**Issue by Bodekaer** [shentao/vue-global-events#8]
Hi @posva,
Really useful addition to Vue! 
I noticed that you haven't yet released 1.0.3 with Filter support.
Any chance you can release that? I'd like to use `npm` to stay up-to-date with future releases.

**Comment by posva** [comment]
Thanks for pointing it out! I completely forgot! It is now published

**Comment by shentao** [comment]
And I’m too late ;C

**Comment by Bodekaer** [comment]
Hehe :) Great stuff! That was fast! 
Just updated and tested here, and it works perfectly.
Thanks so much!
