### ISSUE TITLE
Shift and Ctrl keyup events bug

### ISSUE THREAD

**Issue by Lamberthassel** [shentao/vue-global-events#9]
Keyup events for shift and ctrl keys don't work as intended, other keys are ok though.
Example: https://jsfiddle.net/uem1wkaz/

**Comment by posva** [comment]
they do work 😅 
You will have to provide more info about what isn't working, like steps to reproduce. Closing for the moment

**Comment by posva** [comment]
oooh, now I understand, you meant the keyup event not working!
Let me explain what is happening there, ctrl and shift are modifiers. Therefore the `keyup.prevent.ctrl` only triggers on a keyup **while ctrl is being hold** (same for shift).
This should be doable using a key code though. Let me put up the example

**Comment by posva** [comment]
For control, you will have to write this:

```html
<global-events
  @keydown.prevent.17="plusOne"
  @keyup.prevent.17="minusOne"
/>
```
